# Generated by Django 2.2.3 on 2019-07-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0002_auto_20190705_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_categories_for_dep',
            old_name='departmentid',
            new_name='department',
        ),
    ]
