# Generated by Django 2.2.3 on 2019-07-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0003_auto_20190705_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mealsid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crmfood.Meal_Categories'),
        ),
    ]
