# Generated by Django 2.2.3 on 2019-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0004_auto_20190710_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='mealsid',
        ),
        migrations.AddField(
            model_name='orders',
            name='mealsid',
            field=models.ManyToManyField(to='crmfood.Meal_Categories'),
        ),
    ]
