# Generated by Django 2.2.3 on 2019-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0005_auto_20190710_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mealsid',
            field=models.ManyToManyField(related_name='meal_categories', to='crmfood.Meal_Categories'),
        ),
    ]
