# Generated by Django 2.2.3 on 2019-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0006_auto_20190710_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_orders',
            name='date',
            field=models.DateTimeField(default=True),
        ),
    ]
