# Generated by Django 2.2.3 on 2019-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0007_auto_20190715_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_orders',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mealsid',
            field=models.ManyToManyField(default=True, related_name='meal_categories', to='crmfood.Meal_Categories'),
        ),
    ]
