# Generated by Django 2.2.3 on 2019-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0008_auto_20190715_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
