# Generated by Django 2.2.3 on 2019-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood', '0009_auto_20190715_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
